# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout

      - run: 
          name: Cocoapods update
          command: sudo gem install cocoapods
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install

    test:
        override:
            - set -o pipefail &&
            xcodebuild
                CODE_SIGNING_REQUIRED=NO
                CODE_SIGN_IDENTITY=
                PROVISIONING_PROFILE=
                -sdk iphonesimulator
                -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
                -workspace MyWorkspace.xcworkspace
                -scheme "My Scheme"
                clean build test |
            tee $CIRCLE_ARTIFACTS/xcode_raw.log |
            xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
